/**
 * AlertMind — Report Generator Agent
 * Stage 9: Generates complete incident report in Markdown.
 * Produces both executive summary and full technical report.
 */

import { z } from 'zod';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { llmComplete } from '../llm.service.js';
import { AGENT_NAME } from '../../../shared/constants/ai.constants.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

const SYSTEM_PROMPT = readFileSync(
  join(__dirname, '../../../prompts/system/system.prompt.txt'),
  'utf8'
);
const REPORT_PROMPT = readFileSync(
  join(__dirname, '../../../prompts/report/report.prompt.txt'),
  'utf8'
);

const reportGeneratorOutputSchema = z.object({
  executiveSummary: z.string().min(100).max(2000),
  technicalSummary: z.string().min(100).max(3000),
  markdownContent: z.string().min(200).max(50000),
});

/**
 * @param {object} fullContext - All pipeline results aggregated
 * @returns {Promise<z.infer<typeof reportGeneratorOutputSchema>>}
 */
export async function runReportGeneratorAgent(fullContext) {
  const userPrompt = buildReportPrompt(fullContext);

  return llmComplete({
    agentName: AGENT_NAME.REPORT_GENERATOR,
    modelTier: 'PRIMARY',
    systemPrompt: SYSTEM_PROMPT,
    userPrompt,
    outputSchema: reportGeneratorOutputSchema,
    temperature: 0.15,
    maxTokens: 8192,
  });
}

function buildReportPrompt(ctx) {
  const {
    parsedAlert,
    explanation,
    threatCategory,
    entities,
    mitreMappings,
    hypotheses,
    checklist,
    recommendations,
    riskAssessment,
  } = ctx;

  const now = new Date().toISOString();
  const severity = riskAssessment?.severity || parsedAlert?.severity || 'UNKNOWN';
  const hostname = parsedAlert?.hostname || 'Unknown Host';
  const username = parsedAlert?.username || 'Unknown User';
  const mitreList = mitreMappings?.map((m) => `${m.techniqueId}: ${m.techniqueName}`).join(', ') || 'None identified';
  const iocList = entities?.filter((e) =>
    ['IP_ADDRESS', 'DOMAIN', 'URL', 'MD5', 'SHA1', 'SHA256'].includes(e.type)
  ).map((e) => `- **${e.type}**: \`${e.value}\``).join('\n') || '- None identified';

  const topHypothesis = hypotheses?.[0];
  const criticalRecs = recommendations?.filter((r) => r.priority === 'CRITICAL') || [];
  const highRecs = recommendations?.filter((r) => r.priority === 'HIGH') || [];

  return `${REPORT_PROMPT}

INVESTIGATION RESULTS:
- Report Generated: ${now}
- Severity: ${severity}
- Threat Category: ${threatCategory}
- Host: ${hostname}
- User: ${username}
- MITRE ATT&CK: ${mitreList}
- Business Impact: ${riskAssessment?.businessImpact || 'Not assessed'}
- Requires Immediate Action: ${riskAssessment?.requiresImmediateAction}
- SLA: ${riskAssessment?.recommendedSLALevel} (${riskAssessment?.slaHours}h)
- Primary Hypothesis: ${topHypothesis?.text?.slice(0, 300) || 'None'}
- Likelihood: ${Math.round((riskAssessment?.likelihood || 0) * 100)}%

THREAT EXPLANATION:
${explanation}

IOCs IDENTIFIED:
${iocList}

TASK:
Generate a complete incident report with three parts:

1. executiveSummary (2–4 paragraphs for non-technical leadership):
   - What happened in plain language
   - Business impact and risk
   - What actions were taken or recommended
   - No technical jargon; reference business outcomes not technical indicators

2. technicalSummary (4–8 paragraphs for senior technical staff):
   - Technical description of the attack/event
   - MITRE ATT&CK techniques observed
   - IOCs and entities involved
   - Evidence analysis and confidence levels

3. markdownContent (complete structured report):
   Use this EXACT structure:
   # Incident Report — [Alert Title or Threat Category]
   ## Report Metadata
   ## Executive Summary
   ## Threat Overview
   ## Timeline of Events
   ## Entities & Indicators of Compromise
   ### IP Addresses
   ### Domains & URLs
   ### File Hashes
   ### User Accounts
   ### Processes & Commands
   ## MITRE ATT\&CK Mapping
   ## Investigation Hypotheses
   ## Risk Assessment
   ## Investigation Checklist
   ## Recommended Actions
   ### Immediate Actions (Critical)
   ### Short-term Actions (High Priority)
   ### Long-term Hardening
   ## Analyst Notes
   ---
   *Report generated by AlertMind AI Investigation Platform*

All values in the report must come from the investigation results above.
Do not invent or assume any values not present in the evidence.

Return ONLY the JSON object. No other text.`;
}
